site_name: DCOM

theme:
  name: material
  palette:
    primary: green
  features:
    - navigation.instant

nav:
  - Evaluaci贸n:
    - general: index.md
    - Trabajo grupal: trabajo.md
  - Tema 1:
    - ndice: tema-1/index.md
    - 1. Concepto y naturaleza del producto. Niveles de an谩lisis: tema-1/1.1.md
    - 2. La cartera de productos: tema-1/1.2.md
    - 3. Decisiones sobre marcas, envases y etiquetas: tema-1/1.3.md
    - Tareas: tema-1/tareas.md
  - Tema 2:
    - ndice: tema-2/index.md
    - 1. Concepto de precio. El precio como instrumento de marketing: tema-2/2.1.md
    - 2. Factores condicionantes, objetivos y estrategias en materia de precios: tema-2/2.2.md
    - 3. M茅todos de fijaci贸n y t谩cticas de precios: tema-2/2.3.md
    - Problemas: tema-2/problemas.md
    - Tareas: tema-2/tareas.md
  - Tema 3:
    - ndice: tema-3/index.md
    - 1. La distribuci贸n comercial y los canales de distribuci贸n: tema-3/3.1.md
    - 2. Caracter铆sticas y clasificaci贸n de los comercios mayorista y minorista: tema-3/3.2.md
    - 3. El comercio electr贸nico: tema-3/3.3.md
    - 4. El merchandising: tema-3/3.4.md
    - 5. Tendencias en distribuci贸n: tema-3/3.5.md


repo_name: team-ittade/dcom2
repo_url: https://github.com/team-ittade/dcom2

extra_css:
    - css/colors.css
    - css/custom.css
    - css/termynal.css

extra_javascript:
    - js/config.js
    - js/custom.js
    - js/links.js
    - js/tables.js
    - js/termynal.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - extra
  - extra
  - footnotes
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: 
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - search
